## Failed the first time
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-test/xwiki-platform-annotation-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a3-00finmtnn648o.txt"

## Passed on the ci ?
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00finmymldlx7.txt"

# 1 flicker
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a7-00finmtsf4z8r.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-test/xwiki-platform-flamingo-theme-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a5-00finmtsgnt2d.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a6-00finmu1hy2rj.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a5-00finz889oaa1.txt"

# 1 flicker https://jira.xwiki.org/browse/XWIKI-17483
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fio0i1n2vlh.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-test/xwiki-platform-menu-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a3-00fio0vuw5w4c.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-test/xwiki-platform-mail-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a7-00fio0rc3vl7u.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-test/xwiki-platform-office-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a6-00fio3n7toaym.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fio4gdvcr3n.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-test/xwiki-platform-sharepage-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a3-00fio9b2zzhch.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-directory/xwiki-platform-user-directory-test/xwiki-platform-user-directory-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a7-00fioci4r18mh.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a5-00fiod9n4ptry.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-test/xwiki-platform-vfs-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fioffkc54ei.txt"

# OK
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-test/xwiki-platform-wiki-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.0-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.0 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a3-00fiohh2ua6yn.txt"

# fail locally
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a6-00fioie6jszos.txt"

# FAILED, TODO
# mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-test/xwiki-platform-annotation-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a4-00fioj9dmu9m7.txt"

## Same error as AnnotationIT
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a7-00fiokx4jn0k3.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a3-00fioovgla4wf.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-test/xwiki-platform-flamingo-theme-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a4-00fiophdf54hp.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a4-00fios6w92fa0.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-test/xwiki-platform-menu-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a6-00fiosl9a5eb3.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-test/xwiki-platform-mail-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a5-00fioskz7zniy.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-test/xwiki-platform-office-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a7-00fioth1kjr6x.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a4-00fiowelvyf30.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-test/xwiki-platform-sharepage-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a7-00fiozq07lrng.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-directory/xwiki-platform-user-directory-test/xwiki-platform-user-directory-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a4-00fiozuhzjdbz.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a5-00fip2a06tznm.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-test/xwiki-platform-vfs-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a4-00fip4bbmxuqr.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-test/xwiki-platform-wiki-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mariadb-10.5-pom-jetty-9-firefox -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mariadb -Dxwiki.test.ui.databaseTag=10.5 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=jetty -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=firefox > "Jenkins SSH Slave a6-00fip5349ba1t.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fip6vx33id5.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-test/xwiki-platform-annotation-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a7-00fip70e8xk7r.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a3-00fip91caz66y.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-test/xwiki-platform-flamingo-theme-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fipc3io8cwm.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-test/xwiki-platform-mail-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a7-00fipgkf5u5cb.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a5-00fipgki6p9y5.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-test/xwiki-platform-menu-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a6-00fiphcrx294e.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-test/xwiki-platform-office-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fipj8rye7k8.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-test/xwiki-platform-sharepage-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a3-00fipljue4n0x.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fipljt3mhma.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-directory/xwiki-platform-user-directory-test/xwiki-platform-user-directory-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a7-00fipp8w29d2n.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a5-00fipqissuazo.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-test/xwiki-platform-vfs-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a6-00fiprjkufhb4.txt"
mvn -f pom.xml clean install -Pdocker,legacy,integration-tests,snapshotModules,docker --projects xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-test/xwiki-platform-wiki-test-docker -e -U --no-transfer-progress -Dmaven.test.failure.ignore -Dmaven.build.dir=target/postgresql-13-pom-tomcat-9-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=postgresql -Dxwiki.test.ui.databaseTag=13 -Dxwiki.test.ui.jdbcVersion=pom -Dxwiki.test.ui.servletEngine=tomcat -Dxwiki.test.ui.servletEngineTag=9 -Dxwiki.test.ui.browser=chrome > "Jenkins SSH Slave a4-00fipsxx9s3au.txt"
